### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [mizchi/next-editor#20]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mizchi** [comment]
@mansya welcome project!
I'm not a good designer, so please make log as you like.

We have one requirement. PWA should follow this spec about icon size.
https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by mansya** [comment]
I have design a logo for this project. what do you think ? do you like it ?
![crnotification](https://user-images.githubusercontent.com/33461607/42634593-cf298f7c-860d-11e8-851f-bd2baeee4c58.png)

**Comment by mizchi** [comment]
@mansya Great works! I like this icon, but I think this font is too pop. Do you have any plan for font?

**Comment by mansya** [comment]
what about this font?
![next editor](https://user-images.githubusercontent.com/33461607/42797388-34bfc1ea-89b9-11e8-86ea-d356c8663ad0.png)

**Comment by mansya** [comment]
I have upload all file to this link.
https://drive.google.com/open?id=1Wv-hnjMLhwfEgYffW-6lPPe8AGBWY_zf

And I have sent you pull request. please check

**Comment by mizchi** [comment]
Good. I will accept them (PR merged).
