### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by mizchi** [mizchi/next-editor#243]
- [x] One Pane on mobile(Drawer?)
- [ ] Open safari on ios webview (not wkwebview)

**Comment by rhildred** [comment]
I am hoping to make next-editor work on a phone as a webapp. My thinking was to use react-responsive. I want to start with layout 3 and add items to switch between panes to the GlobalHeader.tsx within <MediaQuery ... elements. 

I think that I am being dense, but I can't find a way to set the initial layout. Would you please point me in the right direction??
